homepage: "https://github.com/amazon-ion/ion-java/"
language: jvm
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/amazon-ion/ion-java/"
sanitizers:
  - address
vendor_ccs:
  - "ion-team@amazon.com"
