homepage: "https://wasmi-labs.github.io/blog/"
main_repo: 'https://github.com/wasmi-labs/wasmi'
primary_contact: "robin.freyler@gmail.com"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
language: rust
